import { useEffect, useRef } from "react";
import { supabase } from "./lib/supabase.js";

const ADMIN_EMAIL="kanshoev.amika@gmail.com";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function imgData(file){return new Promise((res,rej)=>{if(!file||!file.type.startsWith("image/"))return rej(new Error("Выберите файл изображения."));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Не удалось прочитать файл."));r.readAsDataURL(file)})}
async function work(title,year){const a=await supabase.from("media").select("id,title,release_year,poster_url").eq("title",title).maybeSingle();if(a.data)return a.data;const b=await supabase.from("media").select("id,title,release_year,poster_url").ilike("title",title).limit(10);return(b.data||[]).find(x=>!year||Number(x.release_year)===Number(year))||null}
function addControls(){const adminEmail=(window.__frame99UserEmail||"").toLowerCase();if(adminEmail!==ADMIN_EMAIL)return;document.querySelectorAll(".work-card").forEach(card=>{if(card.dataset.frameAdminBridge==="1")return;const title=card.querySelector("h3")?.textContent?.trim();const year=(card.querySelector(".eyebrow")?.textContent||"").match(/·\s*(\d{4})/)?.[1]||null;if(!title)return;card.dataset.frameAdminBridge="1";const bar=document.createElement("div");bar.className="frame-admin-card-actions";const poster=document.createElement("button");poster.type="button";poster.textContent="ПОСТЕР";const del=document.createElement("button");del.type="button";del.textContent="УДАЛИТЬ";poster.onclick=async e=>{e.stopPropagation();const m=await work(title,year);if(!m)return;const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=async()=>{try{const src=await imgData(input.files?.[0]);const{error}=await supabase.rpc("admin_update_media_poster",{p_media_id:m.id,p_poster_url:src,p_position_x:50,p_position_y:50});if(error)throw error;window.location.reload()}catch(err){window.alert(err.message)}};input.click()};del.onclick=async e=>{e.stopPropagation();const m=await work(title,year);if(!m)return;if(!window.confirm(`Удалить «${m.title}» из каталога вместе с оценками и рецензиями?`))return;const{error}=await supabase.rpc("admin_delete_media",{p_media_id:m.id});if(error)return window.alert(error.message);card.remove()};bar.append(poster,del);card.appendChild(bar)})}
export default function AdminPosterBridge(){const userRef=useRef(null);useEffect(()=>{let t;const load=async()=>{const{data}=await supabase.auth.getSession();userRef.current=data.session?.user||null;window.__frame99UserEmail=userRef.current?.email||"";addControls()};load();const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{userRef.current=s?.user||null;window.__frame99UserEmail=userRef.current?.email||"";addControls()});const observer=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(addControls,80)});observer.observe(document.body,{childList:true,subtree:true});return()=>{sub.subscription.unsubscribe();observer.disconnect();clearTimeout(t)}},[]);return null}
