import { useEffect, useRef } from "react";
import { supabase } from "./lib/supabase.js";

const ADMIN_EMAIL="kanshoev.amika@gmail.com";
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function imgData(file){return new Promise((res,rej)=>{if(!file||!file.type.startsWith("image/"))return rej(new Error("Выберите файл изображения."));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(new Error("Не удалось прочитать файл."));r.readAsDataURL(file)})}
async function work(title,year){const a=await supabase.from("media").select("id,title,release_year,poster_url").eq("title",title).maybeSingle();if(a.data)return a.data;const b=await supabase.from("media").select("id,title,release_year,poster_url").ilike("title",title).limit(10);return(b.data||[]).find(x=>!year||Number(x.release_year)===Number(year))||null}
function addControls(){const adminEmail=(window.__frame99UserEmail||"").toLowerCase();if(adminEmail!==ADMIN_EMAIL)return;document.querySelectorAll(".work-card").forEach(card=>{if(card.dataset.frameAdminBridge==="1")return;const title=card.querySelector("h3")?.textContent?.trim();const year=(card.querySelector(".eyebrow")?.textContent||"").match(/·\s*(\d{4})/)?.[1]||null;if(!title)return;card.dataset.frameAdminBridge="1";const bar=document.createElement("div");bar.className="frame-admin-card-actions";const poster=document.createElement("button");poster.type="button";poster.textContent="ПОСТЕР";const del=document.createElement("button");del.type="button";del.textContent="УДАЛИТЬ";poster.onclick=async e=>{e.stopPropagation();const m=await work(title,year);if(!m)return;const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=async()=>{try{const src=await imgData(input.files?.[0]);const{error}=await supabase.rpc("admin_update_media_poster",{p_media_id:m.id,p_poster_url:src,p_position_x:50,p_position_y:50});if(error)throw error;window.location.reload()}catch(err){window.alert(err.message)}};input.click()};del.onclick=async e=>{e.stopPropagation();const m=await work(title,year);if(!m)return;if(!window.confirm(`Удалить «${m.title}» из каталога вместе с оценками и рецензиями?`))return;const{error}=await supabase.rpc("admin_delete_media",{p_media_id:m.id});if(error)return window.alert(error.message);card.remove()};bar.append(poster,del);card.appendChild(bar)})}
async function proposals(){if((window.__frame99UserEmail||"").toLowerCase()!==ADMIN_EMAIL||!document.querySelector(".admin-page"))return;let host=document.querySelector(".frame-admin-proposal-bridge");if(!host){host=document.createElement("section");host.className="admin-section frame-admin-proposal-bridge";document.querySelector(".admin-page")?.appendChild(host)}const{data}=await supabase.from("poster_proposals").select("id,media_id,poster_url,created_at,status").eq("status","pending").order("created_at",{ascending:false});host.innerHTML=`<div class="section-head"><div><span>ПОСТЕРЫ</span><h2>ПРЕДЛОЖЕНИЯ ПОЛЬЗОВАТЕЛЕЙ</h2></div></div>${data?.length?`<div class="frame-proposal-list">${data.map(p=>`<div class="frame-proposal"><img src="${esc(p.poster_url)}" alt=""/><div><b>Предложение постера</b><small>${new Date(p.created_at).toLocaleString("ru-RU")}</small><div class="frame-proposal-actions"><button data-a="${p.id}">ПРИНЯТЬ</button><button data-r="${p.id}">ОТКЛОНИТЬ</button></div></div></div>`).join("")}</div>`:`<div class="empty-state">Новых предложений нет.</div>`}`;host.querySelectorAll("[data-a],[data-r]").forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.a||btn.dataset.r;const{error}=await supabase.rpc("admin_review_poster_proposal",{p_proposal_id:id,p_approve:Boolean(btn.dataset.a)});if(error)window.alert(error.message);else proposals()})}
export default function AdminPosterBridge(){const userRef=useRef(null);useEffect(()=>{let t;const run=async()=>{const{data}=await supabase.auth.getSession();userRef.current=data.session?.user||null;window.__frame99UserEmail=userRef.current?.email||"";addControls();proposals()};run();const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{userRef.current=s?.user||null;window.__frame99UserEmail=userRef.current?.email||"";addControls();proposals()});const observer=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{addControls();proposals()},100)});observer.observe(document.body,{childList:true,subtree:true});return()=>{sub.subscription.unsubscribe();observer.disconnect();clearTimeout(t)}},[]);return null}
